version: "3.9"

services: 
  cloud_storage:
    image: cloud_storage_image
    container_name: cloud_storage
    ports:
      - 2000:80
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
    networks:
      - postgresql_postgres
        
networks:
  postgresql_postgres:
    external: true