// <auto-generated />
using System;
using CloudStorage.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CloudStorage.DAL.Migrations
{
    [DbContext(typeof(CloudStorageUnitOfWork))]
    [Migration("20221227212534_DAL")]
    partial class DAL
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CloudStorage.DAL.Entities.FileDescriptionDbModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("FileDescriptionId");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("FileFolderId")
                        .HasColumnType("integer");

                    b.Property<byte[]>("Preview")
                        .HasColumnType("bytea");

                    b.Property<string>("ProvidedName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SizeInBytes")
                        .HasColumnType("integer");

                    b.Property<string>("UniqueName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UploadedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FileFolderId");

                    b.ToTable("FileDescription");
                });

            modelBuilder.Entity("CloudStorage.DAL.Entities.FileFolderDbModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("FileFolderId");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ParentFolderId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ParentFolderId");

                    b.ToTable("FileFolder");
                });

            modelBuilder.Entity("CloudStorage.DAL.Entities.FileDescriptionDbModel", b =>
                {
                    b.HasOne("CloudStorage.DAL.Entities.FileFolderDbModel", "FileFolder")
                        .WithMany("FileDescriptions")
                        .HasForeignKey("FileFolderId");

                    b.Navigation("FileFolder");
                });

            modelBuilder.Entity("CloudStorage.DAL.Entities.FileFolderDbModel", b =>
                {
                    b.HasOne("CloudStorage.DAL.Entities.FileFolderDbModel", "ParentFolder")
                        .WithMany()
                        .HasForeignKey("ParentFolderId");

                    b.Navigation("ParentFolder");
                });

            modelBuilder.Entity("CloudStorage.DAL.Entities.FileFolderDbModel", b =>
                {
                    b.Navigation("FileDescriptions");
                });
#pragma warning restore 612, 618
        }
    }
}
